### ISSUE TITLE
The generator can produce invalid grids

### ISSUE THREAD

**Issue by Lucas-C** [MorvanZhou/sudoku#1]
Hi.

I was looking for a Python lib that would provide me with a sudoku grid generator,
and I tested yours.

The issue is that it can produces unsolvable grids.

Because :
- the grid is generated simply by applying a random mask, not ensuring it has a solution:
https://github.com/MorvanZhou/sudoku/blob/master/sudoku.py#L25
- your `check_solution` function does not ensure there is a unique deductible solution.
By setting the `mask_rate` to `0.9` the script generates unsolvable grids but still prints `Checked: OK`

I only wish to share share my findings.
It is very nice of you to share your code on GitHub, please do not take this as negative critiscim.

Kind regards

**Comment by MorvanZhou** [comment]
solved
