### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by PySimpleGUI** [MorvanZhou/sudoku#2]
Hi!

I spent some time last night searching through the internet for code that will create a puzzle board.  Yours is by FAR the best I've found.  It's compact and it works without modification.

I have used your generate_puzzle function in my code and want to make sure that I'm abiding by your licensing wishes.  Is it OK to include as part of my project's Demo Programs?  My code is LGPL3.

I have included a link to your project in the header comments and would like to include a little more.  If you have something you would like added specifically, please let me know.

Thank you for your hard work on this!

My PySimpleGUI project homepage:
http://www.PySimpleGUI.com

I'm including my application code below since it's so short.

It produces this window:
![image](https://user-images.githubusercontent.com/46163555/79447639-292be100-7fae-11ea-8120-dc9677718f40.png)

Clicking the Solve button at the moment simply fills in your solved puzzle.  I'll add "score checking" at some point.  The goal of Demo Programs is to show how to build the basics of programs.  They are purposefully lacking in features as the goal is to help people build the framework as a **starting** point.  

```python
import PySimpleGUI as sg, random
import numpy as np

"""
    Sudoku Puzzle Demo
    
    How to easily generate a Sudoku puzzle window.  It can be done in ONE line of code.
    Code to generate a playable puzzle was supplied from:
    https://github.com/MorvanZhou/sudoku
    
    Copyright 2020 PySimpleGUI.com
    
"""
def generate_sudoku(mask_rate=0.5):
    while True:
        n = 9
        m = np.zeros((n, n), np.int)
        rg = np.arange(1, n + 1)
        m[0, :] = np.random.choice(rg, n, replace=False)
        try:
            for r in range(1, n):
                for c in range(n):
                    col_rest = np.setdiff1d(rg, m[:r, c])
                    row_rest = np.setdiff1d(rg, m[r, :c])
                    avb1 = np.intersect1d(col_rest, row_rest)
                    sub_r, sub_c = r//3, c//3
                    avb2 = np.setdiff1d(np.arange(0, n+1), m[sub_r*3:(sub_r+1)*3, sub_c*3:(sub_c+1)*3].ravel())
                    avb = np.intersect1d(avb1, avb2)
                    m[r, c] = np.random.choice(avb, size=1)
            break
        except ValueError:
            pass
    mm = m.copy()
    mm[np.random.choice([True, False], size=m.shape, p=[mask_rate, 1 - mask_rate])] = 0
    return mm, m


def main():
    puzzle, solution = generate_sudoku(mask_rate=0.7)

    window = sg.Window('Sudoku', [[sg.Frame('', [[sg.I(random.randint(1,9), justification='r', size=(3,1), key=(fr*3+r,fc*3+c)) for c in range(3)] for r in range(3)]) for fc in range(3)] for fr in range(3)] +[[sg.B('Solve')]], finalize=True)

    for r, row in enumerate(puzzle):
        for c, col in enumerate(row):
            window[r,c].update(puzzle[r][c] if puzzle[r][c] else '')

    while True:
        event, values = window.read()
        if event is None:
            break
        if event == 'Solve':
            for r, row in enumerate(solution):
                for c, col in enumerate(row):
                    window[r, c].update(solution[r][c] if solution[r][c] else '')

    window.close()

if __name__ == "__main__":
    main()
```

**Comment by MorvanZhou** [comment]
Sure, it is OK for you to use with that citation.
